# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cce9f48efa9b0d5ff74bd111b9cec44de5653a0cdc223d67cd130a7c817e26f87812d0115dd96c716ed7fd38484e2bb102fc7b39c05952de69d3a06a6c595af4

test:
  secret_key_base: cbb7ab380eda847a4daff5324153ef31243f7ebb45e82082e4731d3c2b8e2e4e3c255c19d7524a34aff297a8a5e8c5b3009f569ac953a7932da0bba3c281853b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_KEY_BASE"] %>