---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - [ dom_report, 12 ]
  - [ dom_email, 8 ]
  - [ dom_push, 4 ]
  - [ contest, 1 ]