#!/bin/bash

curl -X POST -H "Content-Type: application/json" \
-d '{}' localhost:3000/users | python -mjson.tool

curl -X POST -H "Content-Type: application/json" \
-d '{ "email" : "pablo.lluch@gmail.com" }' localhost:3000/users | python -mjson.tool

curl -X POST -H "Content-Type: application/json" \
-d '{ "email" : "pablo.lluch@gmail.com", "password" : "12345678", "password_confirmation" : "12345679" }' localhost:3000/users | python -mjson.tool

curl -X POST -H "Content-Type: application/json" \
-d '{ "email" : "pablo.lluch@gmail.com", "password" : "12345678", "password_confirmation" : "12345678" }' localhost:3000/users | python -mjson.tool

curl -X GET localhost:3000/users/1 | python -mjson.tool


